remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

title: "Who Infected the Market?"
description: "Markets don’t fail alone — they infect each other. Who Infected the Market? is a data-driven investigation that treats financial contagion like an epidemic, searching for patient zero and super-spreader stocks through network and time-series analysis."

url: "https://nazarsosyak.github.io"
baseurl: "/adav-group"

show_downloads: true

navigation:
  - title: Home
    url: /
  - title: Example
    url: /example/

defaults:
  - scope:
      path: ""
    values:
      layout: default

